USE DATABASE DBAONTAP_ANALYTICS;
USE WAREHOUSE DBRYANT_COCO_WH_S;

CREATE OR REPLACE DYNAMIC TABLE GOLD.CUSTOMER_360
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = DBRYANT_COCO_WH_S
AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.FIRST_NAME || ' ' || c.LAST_NAME as FULL_NAME,
    c.EMAIL,
    c.PHONE,
    c.COMPANY_NAME,
    c.SEGMENT,
    c.LOYALTY_TIER,
    c.ANNUAL_REVENUE,
    c.CREATED_AT as CUSTOMER_SINCE,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) as LIFETIME_VALUE,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    MIN(o.ORDER_DATE) as FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE,
    DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_DATE()) as RECENCY_DAYS,
    COUNT(DISTINCT o.ORDER_ID) as FREQUENCY,
    SUM(o.TOTAL_AMOUNT) as MONETARY_TOTAL,
    CASE
        WHEN SUM(o.TOTAL_AMOUNT) >= 100000 THEN 'PLATINUM'
        WHEN SUM(o.TOTAL_AMOUNT) >= 50000 THEN 'GOLD'
        WHEN SUM(o.TOTAL_AMOUNT) >= 10000 THEN 'SILVER'
        ELSE 'BRONZE'
    END as REVENUE_TIER,
    CASE
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_DATE()) <= 7 THEN 'HOT'
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_DATE()) <= 30 THEN 'ACTIVE'
        WHEN DATEDIFF('day', MAX(o.ORDER_DATE), CURRENT_DATE()) <= 90 THEN 'COOLING'
        ELSE 'DORMANT'
    END as ENGAGEMENT_STATUS,
    COUNT(DISTINCT t.TICKET_ID) as TOTAL_TICKETS,
    SUM(CASE WHEN t.STATUS = 'open' THEN 1 ELSE 0 END) as OPEN_TICKETS
FROM SILVER.CUSTOMERS c
LEFT JOIN SILVER.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN SILVER.SUPPORT_TICKETS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
WHERE c._SNOWFLAKE_DELETED = FALSE
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.PHONE,
         c.COMPANY_NAME, c.SEGMENT, c.LOYALTY_TIER, c.ANNUAL_REVENUE, c.CREATED_AT;

CREATE OR REPLACE DYNAMIC TABLE GOLD.PRODUCT_PERFORMANCE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = DBRYANT_COCO_WH_S
AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.LIST_PRICE,
    p.COST_PRICE,
    p.LIST_PRICE - p.COST_PRICE as MARGIN,
    CASE WHEN p.LIST_PRICE > 0 THEN ROUND((p.LIST_PRICE - p.COST_PRICE) / p.LIST_PRICE * 100, 2) ELSE 0 END as MARGIN_PERCENT,
    p.SKU,
    p.IS_ACTIVE,
    COUNT(DISTINCT oi.ORDER_ID) as ORDERS_COUNT,
    SUM(oi.QUANTITY) as UNITS_SOLD,
    SUM(oi.LINE_TOTAL) as TOTAL_REVENUE,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS
FROM SILVER.PRODUCTS p
LEFT JOIN SILVER.ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
LEFT JOIN SILVER.ORDERS o ON oi.ORDER_ID = o.ORDER_ID
WHERE p._SNOWFLAKE_DELETED = FALSE
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.LIST_PRICE, p.COST_PRICE, p.SKU, p.IS_ACTIVE;

CREATE OR REPLACE DYNAMIC TABLE GOLD.ORDER_SUMMARY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = DBRYANT_COCO_WH_S
AS
SELECT
    DATE_TRUNC('month', o.ORDER_DATE)::DATE as ORDER_MONTH,
    c.SEGMENT as CUSTOMER_SEGMENT,
    COUNT(DISTINCT o.ORDER_ID) as ORDER_COUNT,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    SUM(CASE WHEN o.STATUS = 'completed' THEN 1 ELSE 0 END) as COMPLETED_ORDERS,
    SUM(CASE WHEN o.STATUS = 'pending' THEN 1 ELSE 0 END) as PENDING_ORDERS,
    SUM(CASE WHEN o.STATUS = 'processing' THEN 1 ELSE 0 END) as PROCESSING_ORDERS
FROM SILVER.ORDERS o
JOIN SILVER.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o._SNOWFLAKE_DELETED = FALSE
GROUP BY ORDER_MONTH, c.SEGMENT;

CREATE OR REPLACE DYNAMIC TABLE GOLD.CUSTOMER_METRICS
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = DBRYANT_COCO_WH_S
AS
SELECT
    c.SEGMENT,
    c.LOYALTY_TIER,
    COUNT(DISTINCT c.CUSTOMER_ID) as CUSTOMER_COUNT,
    SUM(COALESCE(o.ORDER_COUNT, 0)) as TOTAL_ORDERS,
    SUM(COALESCE(o.TOTAL_AMOUNT, 0)) as TOTAL_REVENUE,
    AVG(COALESCE(o.ORDER_COUNT, 0)) as AVG_ORDERS_PER_CUSTOMER
FROM SILVER.CUSTOMERS c
LEFT JOIN (
    SELECT CUSTOMER_ID, COUNT(*) as ORDER_COUNT, SUM(TOTAL_AMOUNT) as TOTAL_AMOUNT
    FROM SILVER.ORDERS WHERE _SNOWFLAKE_DELETED = FALSE
    GROUP BY CUSTOMER_ID
) o ON c.CUSTOMER_ID = o.CUSTOMER_ID
WHERE c._SNOWFLAKE_DELETED = FALSE
GROUP BY c.SEGMENT, c.LOYALTY_TIER;

CREATE OR REPLACE DYNAMIC TABLE GOLD.ML_CUSTOMER_FEATURES
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = DBRYANT_COCO_WH_S
AS
SELECT
    c.CUSTOMER_ID,
    c.SEGMENT,
    c.LOYALTY_TIER,
    COALESCE(c360.TOTAL_ORDERS, 0) as TOTAL_ORDERS,
    COALESCE(c360.LIFETIME_VALUE, 0) as LIFETIME_VALUE,
    COALESCE(c360.AVG_ORDER_VALUE, 0) as AVG_ORDER_VALUE,
    COALESCE(c360.RECENCY_DAYS, 999) as RECENCY_DAYS,
    COALESCE(c360.TOTAL_TICKETS, 0) as TOTAL_TICKETS,
    CASE c.SEGMENT WHEN 'ENTERPRISE' THEN 3 WHEN 'MID-MARKET' THEN 2 ELSE 1 END as SEGMENT_ENCODED,
    CASE c360.REVENUE_TIER
        WHEN 'PLATINUM' THEN 4 WHEN 'GOLD' THEN 3 WHEN 'SILVER' THEN 2 ELSE 1
    END as TIER_ENCODED,
    CASE WHEN c360.ENGAGEMENT_STATUS = 'DORMANT' THEN 1 ELSE 0 END as IS_CHURNED
FROM SILVER.CUSTOMERS c
LEFT JOIN GOLD.CUSTOMER_360 c360 ON c.CUSTOMER_ID = c360.CUSTOMER_ID
WHERE c._SNOWFLAKE_DELETED = FALSE;
