USE DATABASE DBAONTAP_ANALYTICS;
USE WAREHOUSE DBRYANT_COCO_WH_S;

CREATE OR REPLACE STREAMLIT DBAONTAP_ANALYTICS.METADATA.DEMO_MANAGER
    ROOT_LOCATION = '@DBAONTAP_ANALYTICS.METADATA.STREAMLIT_STAGE'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = DBRYANT_COCO_WH_S
    EXTERNAL_ACCESS_INTEGRATIONS = (DBAONTAP_PG_EAI)
    SECRETS = ('pg_source_creds' = DBAONTAP_ANALYTICS.METADATA.PG_SOURCE_SECRET,
               'pg_landing_creds' = DBAONTAP_ANALYTICS.METADATA.PG_LANDING_SECRET)
    COMMENT = 'Agentic Silver Layer Demo Manager with full workflow engine and PostgreSQL EAI';

GRANT USAGE ON STREAMLIT DBAONTAP_ANALYTICS.METADATA.DEMO_MANAGER TO ROLE ACCOUNTADMIN;

SHOW STREAMLITS LIKE 'DEMO_MANAGER' IN SCHEMA DBAONTAP_ANALYTICS.METADATA;
