-- =============================================================================
-- AI CONSUMPTION LAYER
-- Semantic Views, Cortex Agent, ML Integration, Feedback Loop
-- =============================================================================

USE DATABASE AGENTIC_PIPELINE;

-- ============================================================================
-- PART 1: SEMANTIC VIEWS FOR CORTEX ANALYST
-- Business vocabulary layer for natural language queries
-- ============================================================================

-- Customer 360 Semantic View
CREATE OR REPLACE SEMANTIC VIEW GOLD.CUSTOMER_360_SEMANTIC
AS SELECT * FROM GOLD.PG_CUSTOMER_360
COMMENT = 'Customer analytics with lifetime value, engagement metrics, and churn indicators'
WITH SEMANTIC MODEL (
    tables:
      - name: PG_CUSTOMER_360
        description: "Comprehensive customer view combining profile data with order history and engagement metrics"
        columns:
          - name: CUSTOMER_ID
            description: "Unique customer identifier from source Postgres system"
            data_type: INTEGER
          - name: FULL_NAME
            description: "Customer full name"
            data_type: VARCHAR
          - name: COMPANY_NAME
            description: "Customer company or organization name"
            data_type: VARCHAR
          - name: SEGMENT
            description: "Customer segment classification"
            data_type: VARCHAR
            sample_values: ["ENTERPRISE", "MID-MARKET", "SMB"]
          - name: REVENUE_TIER
            description: "Revenue-based tier classification"
            data_type: VARCHAR
            sample_values: ["ENTERPRISE", "MID-MARKET", "SMB"]
          - name: ANNUAL_REVENUE
            description: "Customer annual revenue in dollars"
            data_type: NUMBER
          - name: LIFETIME_VALUE
            description: "Total revenue from customer across all orders"
            data_type: NUMBER
            synonyms: ["LTV", "customer value", "total spend", "CLV"]
          - name: AVG_ORDER_VALUE
            description: "Average order amount"
            data_type: NUMBER
            synonyms: ["AOV", "basket size", "average purchase"]
          - name: TOTAL_ORDERS
            description: "Total number of orders placed by customer"
            data_type: INTEGER
            synonyms: ["order count", "number of orders", "purchases"]
          - name: DAYS_SINCE_LAST_ORDER
            description: "Days since customer last placed an order"
            data_type: INTEGER
            synonyms: ["recency", "last purchase days ago", "inactive days"]
          - name: ENGAGEMENT_STATUS
            description: "Current engagement level based on recency"
            data_type: VARCHAR
            sample_values: ["HOT", "ACTIVE", "COOLING", "AT_RISK"]
            synonyms: ["status", "health", "activity level"]
);

-- Product Performance Semantic View
CREATE OR REPLACE SEMANTIC VIEW GOLD.PRODUCT_PERFORMANCE_SEMANTIC
AS SELECT * FROM GOLD.PG_PRODUCT_PERFORMANCE
COMMENT = 'Product analytics with sales metrics and customer reach'
WITH SEMANTIC MODEL (
    tables:
      - name: PG_PRODUCT_PERFORMANCE
        description: "Product-level analytics showing sales performance and customer adoption"
        columns:
          - name: PRODUCT_ID
            description: "Unique product identifier"
            data_type: INTEGER
          - name: SKU
            description: "Stock keeping unit code"
            data_type: VARCHAR
          - name: PRODUCT_NAME
            description: "Product display name"
            data_type: VARCHAR
            synonyms: ["name", "product"]
          - name: CATEGORY
            description: "Product category"
            data_type: VARCHAR
          - name: LIST_PRICE
            description: "Standard list price in dollars"
            data_type: NUMBER
            synonyms: ["price", "cost", "retail price"]
          - name: TOTAL_UNITS_SOLD
            description: "Total quantity sold across all orders"
            data_type: INTEGER
            synonyms: ["units sold", "quantity sold", "volume"]
          - name: TOTAL_REVENUE
            description: "Total revenue generated by this product"
            data_type: NUMBER
            synonyms: ["sales", "revenue", "income"]
          - name: UNIQUE_CUSTOMERS
            description: "Number of unique customers who purchased this product"
            data_type: INTEGER
            synonyms: ["customer count", "buyers"]
);

-- ============================================================================
-- PART 2: CORTEX AGENT FOR CUSTOMER INTELLIGENCE
-- AI assistant for sales and customer success teams
-- ============================================================================

CREATE OR REPLACE AGENT AGENTS.CUSTOMER_INTELLIGENCE_AGENT
  COMMENT = 'AI assistant for customer analytics, churn prediction, and sales recommendations'
  PROFILE = '{"display_name": "Customer Intelligence", "avatar": "chart", "color": "#29B5E8"}'
  FROM SPECIFICATION $$
  {
    "models": {
      "orchestration": "claude-4-sonnet"
    },
    "instructions": {
      "orchestration": "You are a customer intelligence assistant helping sales and customer success teams. You can: 1) Query customer analytics using natural language, 2) Identify at-risk customers, 3) Recommend next best actions, 4) Analyze product performance. Always provide actionable insights.",
      "response": "Be concise and actionable. When showing customer data, highlight engagement status and recommended actions. Format numbers with appropriate currency symbols and commas.",
      "system": "You help business users understand customer health, identify opportunities, and take action to improve retention and growth."
    },
    "tools": [
      {
        "tool_spec": {
          "type": "cortex_analyst",
          "name": "customer_analytics",
          "description": "Query customer data including lifetime value, order history, and engagement metrics"
        },
        "tool_resources": {
          "semantic_view": "AGENTIC_PIPELINE.GOLD.CUSTOMER_360_SEMANTIC"
        }
      },
      {
        "tool_spec": {
          "type": "cortex_analyst",
          "name": "product_analytics",
          "description": "Query product performance including sales volume, revenue, and customer adoption"
        },
        "tool_resources": {
          "semantic_view": "AGENTIC_PIPELINE.GOLD.PRODUCT_PERFORMANCE_SEMANTIC"
        }
      },
      {
        "tool_spec": {
          "type": "system_execute_sql",
          "name": "run_analysis",
          "description": "Execute custom SQL queries for advanced analysis"
        }
      }
    ],
    "tool_resources": {
      "run_analysis": {
        "type": "sql",
        "execution_environment": {
          "type": "warehouse",
          "warehouse": "SNOWADHOC"
        }
      }
    }
  }
  $$;

GRANT USAGE ON AGENT AGENTS.CUSTOMER_INTELLIGENCE_AGENT TO ROLE PUBLIC;

-- ============================================================================
-- PART 3: ML FEATURE ACCESS (For Data Scientists)
-- Clean interface for ML model training
-- ============================================================================

-- View optimized for ML consumption
CREATE OR REPLACE VIEW GOLD.ML_CUSTOMER_FEATURES AS
SELECT
    customer_id,
    -- Categorical features (one-hot encode these)
    segment,
    revenue_tier,
    engagement_status,
    -- Numerical features (normalize these)
    annual_revenue,
    customer_tenure_days,
    recency_days,
    order_count,
    orders_per_month,
    total_spend,
    avg_order_value,
    max_order_value,
    order_value_stddev,
    unique_products_purchased,
    engagement_score,
    -- Target variable
    churn_flag
FROM GOLD.PG_SALES_FEATURES;

-- ============================================================================
-- PART 4: AI FEEDBACK LOOP
-- Write insights back to source Postgres for operational use
-- ============================================================================

-- Table to stage AI-generated insights (would sync back to Postgres)
CREATE OR REPLACE TABLE GOLD.AI_CUSTOMER_INSIGHTS (
    insight_id VARCHAR DEFAULT UUID_STRING(),
    customer_id INTEGER,
    insight_type VARCHAR,           -- 'CHURN_RISK', 'UPSELL_OPPORTUNITY', 'ENGAGEMENT_ALERT'
    insight_severity VARCHAR,       -- 'HIGH', 'MEDIUM', 'LOW'
    recommendation TEXT,
    supporting_data VARIANT,
    generated_by VARCHAR DEFAULT 'CORTEX_AGENT',
    generated_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    synced_to_postgres BOOLEAN DEFAULT FALSE,
    actioned BOOLEAN DEFAULT FALSE
);

-- Procedure to generate insights from Gold data
CREATE OR REPLACE PROCEDURE AGENTS.GENERATE_CUSTOMER_INSIGHTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    -- Churn Risk Insights
    INSERT INTO GOLD.AI_CUSTOMER_INSIGHTS (customer_id, insight_type, insight_severity, recommendation, supporting_data)
    SELECT 
        customer_id,
        'CHURN_RISK',
        CASE 
            WHEN days_since_last_order > 90 AND lifetime_value > 50000 THEN 'HIGH'
            WHEN days_since_last_order > 60 THEN 'MEDIUM'
            ELSE 'LOW'
        END,
        CASE 
            WHEN days_since_last_order > 90 THEN 'URGENT: Schedule executive call - high value customer at risk'
            WHEN days_since_last_order > 60 THEN 'Send personalized re-engagement email with special offer'
            ELSE 'Monitor - proactive check-in recommended'
        END,
        OBJECT_CONSTRUCT(
            'days_inactive', days_since_last_order,
            'lifetime_value', lifetime_value,
            'segment', segment
        )
    FROM GOLD.PG_CUSTOMER_360
    WHERE engagement_status IN ('AT_RISK', 'COOLING')
      AND customer_id NOT IN (SELECT customer_id FROM GOLD.AI_CUSTOMER_INSIGHTS WHERE insight_type = 'CHURN_RISK' AND generated_at > DATEADD('day', -7, CURRENT_TIMESTAMP()));
    
    -- Upsell Opportunities
    INSERT INTO GOLD.AI_CUSTOMER_INSIGHTS (customer_id, insight_type, insight_severity, recommendation, supporting_data)
    SELECT 
        customer_id,
        'UPSELL_OPPORTUNITY',
        'MEDIUM',
        'Customer shows growth potential - recommend premium tier upgrade',
        OBJECT_CONSTRUCT(
            'current_tier', revenue_tier,
            'order_frequency', total_orders,
            'avg_order_value', avg_order_value
        )
    FROM GOLD.PG_CUSTOMER_360
    WHERE engagement_status = 'HOT'
      AND revenue_tier = 'SMB'
      AND total_orders >= 3
      AND customer_id NOT IN (SELECT customer_id FROM GOLD.AI_CUSTOMER_INSIGHTS WHERE insight_type = 'UPSELL_OPPORTUNITY' AND generated_at > DATEADD('day', -30, CURRENT_TIMESTAMP()));
    
    RETURN 'Insights generated successfully';
END;
$$;

-- ============================================================================
-- PART 5: EXAMPLE QUERIES
-- Demonstrating the AI consumption patterns
-- ============================================================================

-- Natural Language → SQL (via Cortex Analyst)
-- "Show me enterprise customers at risk of churning"
SELECT 
    customer_id,
    full_name,
    company_name,
    lifetime_value,
    days_since_last_order,
    engagement_status
FROM GOLD.PG_CUSTOMER_360
WHERE segment = 'ENTERPRISE' 
  AND engagement_status = 'AT_RISK'
ORDER BY lifetime_value DESC;

-- "What are our top selling products this quarter?"
SELECT 
    product_name,
    category,
    total_units_sold,
    total_revenue,
    unique_customers
FROM GOLD.PG_PRODUCT_PERFORMANCE
WHERE is_active = TRUE
ORDER BY total_revenue DESC
LIMIT 10;

-- ML Feature Query
SELECT * FROM GOLD.ML_CUSTOMER_FEATURES WHERE churn_flag = 1;

-- Generate new insights
-- CALL AGENTS.GENERATE_CUSTOMER_INSIGHTS();

-- View generated insights
SELECT * FROM GOLD.AI_CUSTOMER_INSIGHTS ORDER BY generated_at DESC;
