-- =============================================================================
-- CLEANUP SCRIPT
-- Drop all objects created by the Agentic Silver Layer demo
-- =============================================================================

-- Drop Dynamic Tables first (they depend on base tables)
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.GOLD.SALES_SUMMARY;
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.GOLD.CUSTOMER_360;
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.SILVER.PRODUCTS;
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.SILVER.ORDER_ITEMS;
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.SILVER.ORDERS;
DROP DYNAMIC TABLE IF EXISTS AGENTIC_PIPELINE.SILVER.CUSTOMERS;

-- Drop Tasks
DROP TASK IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_WATCHER_TASK;

-- Drop Streams
DROP STREAM IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_CUSTOMERS_STREAM;
DROP STREAM IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_ORDERS_STREAM;
DROP STREAM IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_PRODUCTS_STREAM;

-- Drop Agent
DROP AGENT IF EXISTS AGENTIC_PIPELINE.AGENTS.SILVER_TRANSFORMATION_AGENT;

-- Drop Semantic View
DROP SEMANTIC VIEW IF EXISTS AGENTIC_PIPELINE.AGENTS.BRONZE_METADATA_VIEW;

-- Drop Views
DROP VIEW IF EXISTS AGENTIC_PIPELINE.METADATA.TRANSFORMATION_LINEAGE;
DROP VIEW IF EXISTS AGENTIC_PIPELINE.METADATA.GOLD_CATALOG;
DROP VIEW IF EXISTS AGENTIC_PIPELINE.METADATA.SILVER_CATALOG;
DROP VIEW IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_CATALOG;

-- Drop Procedures
DROP PROCEDURE IF EXISTS AGENTIC_PIPELINE.AGENTS.REFLECT_ON_WORKFLOW(VARCHAR);
DROP PROCEDURE IF EXISTS AGENTIC_PIPELINE.AGENTS.RUN_TRANSFORMATION_WORKFLOW(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS AGENTIC_PIPELINE.AGENTS.CORTEX_INFER_SCHEMA(VARCHAR);
DROP PROCEDURE IF EXISTS AGENTIC_PIPELINE.AGENTS.GENERATE_TRANSFORMATION(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS AGENTIC_PIPELINE.AGENTS.ANALYZE_DATA_QUALITY(VARCHAR, NUMBER);

-- Drop Functions
DROP FUNCTION IF EXISTS AGENTIC_PIPELINE.AGENTS.DISCOVER_SCHEMA(VARCHAR);

-- Drop Tables
DROP TABLE IF EXISTS AGENTIC_PIPELINE.METADATA.AGENT_REFLECTIONS;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.METADATA.WORKFLOW_STATE;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.METADATA.TRANSFORMATION_LOG;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.METADATA.BRONZE_SCHEMA_REGISTRY;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.BRONZE.RAW_PRODUCTS;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.BRONZE.RAW_ORDERS;
DROP TABLE IF EXISTS AGENTIC_PIPELINE.BRONZE.RAW_CUSTOMERS;

-- Drop Schemas
DROP SCHEMA IF EXISTS AGENTIC_PIPELINE.METADATA;
DROP SCHEMA IF EXISTS AGENTIC_PIPELINE.AGENTS;
DROP SCHEMA IF EXISTS AGENTIC_PIPELINE.GOLD;
DROP SCHEMA IF EXISTS AGENTIC_PIPELINE.SILVER;
DROP SCHEMA IF EXISTS AGENTIC_PIPELINE.BRONZE;

-- Drop Database
DROP DATABASE IF EXISTS AGENTIC_PIPELINE;

SELECT 'Cleanup complete. All Agentic Pipeline objects have been removed.' as status;
